/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.u1a4a2_sleep;

/**
 *
 * @author alfiea
 */
public class U1A4A2_Sleep extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(U1A4A2_Sleep.class.getName());

    /**
     * Creates new form U1A4A2_Sleep
     */
    public U1A4A2_Sleep() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        birthday = new javax.swing.JLabel();
        todayDate = new javax.swing.JLabel();
        bDayLabel = new javax.swing.JLabel();
        bDayText = new javax.swing.JTextField();
        bMonthLabel = new javax.swing.JLabel();
        bMonthText = new javax.swing.JTextField();
        bYearLabel = new javax.swing.JLabel();
        bYearText = new javax.swing.JTextField();
        tDayLabel = new javax.swing.JLabel();
        tDayText = new javax.swing.JTextField();
        tMonthLabel = new javax.swing.JLabel();
        tMonthText = new javax.swing.JTextField();
        tYearLabel = new javax.swing.JLabel();
        tYearText = new javax.swing.JTextField();
        calculate = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        daysAliveForText = new javax.swing.JTextField();
        hoursSleptText = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        title.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 24)); // NOI18N
        title.setForeground(new java.awt.Color(0, 107, 16));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Sleep Calculator");

        birthday.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 14)); // NOI18N
        birthday.setForeground(new java.awt.Color(0, 86, 161));
        birthday.setText("Enter Your Birthdate");

        todayDate.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 14)); // NOI18N
        todayDate.setForeground(new java.awt.Color(0, 86, 161));
        todayDate.setText("Enter Today's Date");

        bDayLabel.setText("Day:");

        bMonthLabel.setText("Month:");

        bYearLabel.setText("Year: ");

        tDayLabel.setText("Day:");

        tDayText.addActionListener(this::tDayTextActionPerformed);

        tMonthLabel.setText("Month:");

        tYearLabel.setText("Year: ");

        calculate.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 14)); // NOI18N
        calculate.setForeground(new java.awt.Color(0, 107, 16));
        calculate.setText("Calculate");
        calculate.setBorder(null);
        calculate.addActionListener(this::calculateActionPerformed);

        exit.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 14)); // NOI18N
        exit.setForeground(new java.awt.Color(0, 107, 16));
        exit.setText("Exit");
        exit.setBorder(null);
        exit.addActionListener(this::exitActionPerformed);

        daysAliveForText.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N

        hoursSleptText.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bYearLabel)
                                    .addComponent(bDayLabel))
                                .addGap(72, 72, 72)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(bMonthText, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                                    .addComponent(bYearText)
                                    .addComponent(bDayText)))
                            .addComponent(bMonthLabel)
                            .addComponent(birthday))
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(todayDate)
                                .addGap(106, 106, 106))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tYearLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tYearText, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tMonthLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tMonthText, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(tDayLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tDayText, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(68, 68, 68))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(calculate, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(106, 106, 106)
                                .addComponent(daysAliveForText, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(106, 106, 106)
                                .addComponent(hoursSleptText)))
                        .addGap(209, 209, 209))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(title)
                .addGap(313, 313, 313))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(title)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(birthday)
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bDayLabel)
                            .addComponent(bDayText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bMonthLabel)
                            .addComponent(bMonthText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bYearLabel)
                            .addComponent(bYearText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tYearLabel)
                            .addComponent(tYearText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(todayDate)
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tMonthLabel)
                                    .addComponent(tMonthText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tDayText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tDayLabel)))))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(calculate, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(daysAliveForText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hoursSleptText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tDayTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tDayTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tDayTextActionPerformed

    private void calculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateActionPerformed
        // b = birthday 
        // t = today
        
        // get birthday
        int bDay = Integer.parseInt(bDayText.getText());
        int bMonth = Integer.parseInt(bMonthText.getText());
        int bYear = Integer.parseInt(bYearText.getText());
        
        // get today's date
        int tDay = Integer.parseInt(tDayText.getText());
        int tMonth = Integer.parseInt(tMonthText.getText());
        int tYear = Integer.parseInt(tYearText.getText());
        
        // define person's age
        int years = 0;
        int months = 0;
        int days = 0;
        
        // validate the input
        if (bYear > tYear) {
            // set the text
            System.exit(0);
        }
        
        // check if the birthday has already passed
        if (bMonth < tMonth) {
            years = tYear - bYear;
            months = tMonth - bMonth;
            days = tDay - bDay;
            
        } else if (bMonth == tMonth) {
            if (bDay < tDay) {
                years = tYear - bYear;
                months = 0;
                days = tDay - bDay;
            } else if (bDay == tDay) {
                years = tYear - bYear;
                months = 0;
                days = 0;
            } else {
                years = tYear - (bYear - 1); // birthday hasen't happened
                months = 11; // right before birthday
                days = tDay;
            }
        } else {
            // bMonth > tMonth
            years = tYear - (bYear - 1);
            months = tMonth;
            days = tDay;
        }
        
        // calculate days lived
        int daysLived = (years * 365) + (months * 30) + days;
        int hoursSlept = daysLived * 8;
        
        String daysMsg = "You have been alive for " + daysLived + " days.";
        String sleepMsg = "You have slept " + hoursSlept + " hours.";
        
        // set text
        daysAliveForText.setText(daysMsg);
        hoursSleptText.setText(sleepMsg);
        
    }//GEN-LAST:event_calculateActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new U1A4A2_Sleep().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bDayLabel;
    private javax.swing.JTextField bDayText;
    private javax.swing.JLabel bMonthLabel;
    private javax.swing.JTextField bMonthText;
    private javax.swing.JLabel bYearLabel;
    private javax.swing.JTextField bYearText;
    private javax.swing.JLabel birthday;
    private javax.swing.JButton calculate;
    private javax.swing.JTextField daysAliveForText;
    private javax.swing.JButton exit;
    private javax.swing.JTextField hoursSleptText;
    private javax.swing.JLabel tDayLabel;
    private javax.swing.JTextField tDayText;
    private javax.swing.JLabel tMonthLabel;
    private javax.swing.JTextField tMonthText;
    private javax.swing.JLabel tYearLabel;
    private javax.swing.JTextField tYearText;
    private javax.swing.JLabel title;
    private javax.swing.JLabel todayDate;
    // End of variables declaration//GEN-END:variables
}
